### ISSUE TITLE
Migrating from AWS KMS java sdk

### ISSUE THREAD

**Issue by schmohlio** [aws/aws-encryption-sdk-java#112]
Greetings,

Articles such as these https://aws.amazon.com/blogs/security/aws-encryption-sdk-how-to-decide-if-data-key-caching-is-right-for-your-application/ tout the benefits of introducing caching if you are hitting KMS limits. 

Our teams were interested in migrating to the encryption SDK, but were surprised to see that this migration is not backwards compatible with the ciphertext previously encrypted directly with the AWS java SDK KMS service. 

Are there any known ways to re-encode data to match the message formats?

**Comment by mattsb42-aws** [comment]
Hi @schmohlio,

When you talk about backwards compatibility, do you mean code on your end understanding how to decrypt both data that was encrypted using KMS directly *and* data that was encrypted using the AWS Encryption SDK or do you mean being able to decrypt using KMS directly data that was encrypted using the AWS Encryption SDK?

The former is fairly straightforward. The later is intentionally not possible.

**Comment by schmohlio** [comment]
Hi @mattsb42-aws - thanks for response. 

I have a collection of encrypted data, i.e., `[ciphertext_1, ciphertext_2,... ciphertext_i]` that was previously encrypted with the AWS KMS Api (SDK) by calling the `encrypt()` command with CMK_1.

I'd now like to use the Encryption SDK with caching, where my `MasterKeyProvider` is the same keyId, CMK_1. I'm wondering if there is a way to decrypt my existing ciphertext that I've persisted, using the Encryption SDK.

I believe this is the former strategy. One thing I'm confused about is if the the Data Keys cached by the Encryption SDK are within the same chain of trust (are they just intermediate keys?), and will be able to decrypt data historically encrypted by calling the `encrypt()` command with KMS. If so, do they need to be reencoded?

**Comment by mattsb42-aws** [comment]
Ok, that's pretty straightforward, then.

Before I start into that, though, I do want to note that if the *only* reason you are looking at data key caching is because you are hitting KMS limits, those limits can be raised.

Any data key reuse is a trade-off between security and cost (whether latency, financial, etc). Because you are not calling KMS for every message, IAM and KMS are not authorizing the key use for every message and you do not get CloudTrail records for every message. These still happen on cache misses, but since the point of caching is to reduce your calls to KMS, those calls do not happen on cache hits. Whether, and to what degree, this trade-off is reasonable depends on your application and threat model.

Because of this, we recommend limit increases rather than data key caching if the API limits are the *only* reason that you are looking at caching.

If you do decide to use caching, we recommend that you set the caching thresholds[5] as low as possible. You can always turn them up later if you need to.

----

**Migrating from direct KMS encryption to the AWS Encryption SDK**

KMS and the AWS Encryption SDK use separate and incompatible data formats. Because of this, you cannot convert to and from the KMS ciphertext without actually calling KMS. The KMS service also cannot decrypt mesages that were encrypted using the AWS Encryption SDK.

When people are looking to make this move, the pattern we generally recommend is that rather than re-processing all of your data at once, you instead modify your read logic to work with either approach and only write in the new format. That way, you can migrate the formats without any downtime, either directly or over time as your application naturally reads and writes data.

Assuming you don't need to deal with streaming data, the simplest way to approach this is to attempt to parse the ciphertext using `ParsedCiphertext`[1].

If that succeeds, the ciphertext uses the AWS Encryption SDK format and you can pass it to `AWSCrypto.decryptData`[2] along with your master key provider (MKP) or cryptographic materials manager (CMM).

If it is a KMS ciphertext, attempting to load it using `ParsedCiphertext` will throw a `BadCiphertextException`[3], and you can then call KMS directly with that ciphertext instead.

If you want to add an additional level of certainty that this is a ciphertext that you are expecting, and not just something that happens to match the Encryption SDK format, you can inspect the encrypted data keys in the parsed ciphertext[4] to verify that the message was encrypted using the master key(s) that you are expecting.

----

**Cached data key chain of trust**

> One thing I'm confused about is if the the Data Keys cached by the Encryption SDK are within the same chain of trust (are they just intermediate keys?), and will be able to decrypt data historically encrypted by calling the encrypt() command with KMS. If so, do they need to be reencoded?

When you use the caching CMM, it does not change the key hierarchy at all; it simply stores data keys obtained from the backing CMM (or MKP), and reuses them for future requests within the reuse thresholds[5] that you defined. This is one reason why the caching CMM will only reuse data keys across messages using an algorithm suite that defines a key derivation function[6].

Because of this, each individual encrypted message is indistinguishable from a message that was encrypted using the same MKP *without* the caching CMM, and can be decrypted using that MKP alone *without* caching.


[1] https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/ParsedCiphertext.html
[2] https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/AwsCrypto.html
[3] https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/exception/BadCiphertextException.html
[4] https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/model/CiphertextHeaders.html#getEncryptedKeyBlobs()
[5] https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/thresholds.html
[6] https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/data-caching-details.html

**Comment by schmohlio** [comment]
This is super helpful, thanks @mattsb42-aws . I think I understand the steps to follow and feasibility, if you want to close the ticket.

**Comment by mattsb42-aws** [comment]
Great! If you run into any other questions, please don't hesitate to reach out again.
