### ISSUE TITLE
Need to generate data key without plaintext

### ISSUE THREAD

**Issue by disrael-globality** [aws/aws-encryption-sdk-java#1783]
### Problem:

I need to generate a MasterKey with only the kms:GenerateDataKeyWithoutPlaintext. The MasterKeyProvider implementations are all providing keys that call generateDataKey, which requires the kms:GenerateDataKey permission

There doesn't appear to be an example (anywhere) how to do this.

### Solution:

A possible solution would be a provider/masterkey pair that uses the generateDataKeyWithoutPlaintest method. Or perhaps providing a configuration where I can specify which to use.

**Comment by texastony** [comment]
@disrael-globality,

The result of KMS `GenerateDataKey` includes both the 
encrypted Data Key and the plaintext data key.

This library uses the plaintext data key 
for the content encryption.

If the library invoked `GenerateDataKeyWithoutPlaintext`,
the library would have to invoke `Decrypt` to retrieve
the plaintext data key so that it could do the content encryption.
That is an additional KMS request.

Furthermore, 
if a user of this library separates there Encryptors from their Decryptors,
their Encrytpors may only have KMS `GenerateDataKey` & `Encrypt`
permissions.
While the decryptors would only have `Decrypt` permission.

For these reasons,
we are reluctant to implement a `GenerateDataKeyWithoutPlaintext`
KMS Key Provider.

But maybe we are missing an important use case.

Can you describe how you envision `GenerateDataKeyWithoutPlaintext`
would be used?

Alternatively, if you really want this,
you can [implement your own `MasterKey`](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/MasterKey.java) that
calls `GenerateDataKeyWithoutPlaintext` and then
`Decrypt`.

You would largely copy [`KmsMasterKey`](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/KmsMasterKey.java).
But you [would replace `KmsMasterKey#generateDataKey`](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/KmsMasterKey.java#L82-L114)
with Generate & then Decrypt logic 
specified earlier.

Technically, 
you can even use the same `providerId`,
as the Decrypt behavior is not modified.

Again, I encourage you to think about
how your application benefits from this feature.

If you want to read more details about the behavior
of this library, here are some relevant links to our Specification:
- [Master Key Interface](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/master-key-interface.md)
- [Master Key Provider Interface](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/master-key-provider-interface.md)
- [KMS Master Key Provider](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/aws-kms/aws-kms-mrk-aware-master-key-provider.md)
- [KMS Master Key](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/aws-kms/aws-kms-mrk-aware-master-key.md)

Leaving this issue open, pending a reply.
Will eventually close if no reply is given.

**Comment by disrael-globality** [comment]
Hi @texastony Thanks for your response.

The reason I'm going down this path is that I'm utilizing client provided keys, and some clients are requiring that we support GenerateDataKeyWithoutPlaintext and not GenerateDataKey.

Already implementing something like your proposed solution, but as you note, I would "largely copy [KmsMasterKey](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/KmsMasterKey.java)" (actually, would largely copy [KmsMasterKeyProvider](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/KmsMasterKeyProvider.java) too...). If most of the code is duplicated, it's surprising there is no supported way of extending (without all the duplication). If that's really the only solution, we'll keep what we have.

**Comment by texastony** [comment]
@disrael-globality 

[Integrating Keyrings](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/keyring-interface.md) into the AWS Encryption SDK for Java (ESDK-Java)
is on our roadmap.

Keyrings are easier to implement/extend than MasterKey and MasterKeyProviders,
as the interface is "tighter".

Once we have Keyring support in the ESDK-Java
(particularly the [KMS Keyring](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/aws-kms/aws-kms-keyring.md#onencrypt))
developing a custom Keyring that uses 
`GenerateDataKeyWithoutPlaintext` & `Decrypt`
to determine the plaintext data key SHOULD be easier.

(I am afraid I cannot commit to a date for the completion of this work.)

Again, 
I do not think we will ever natively support this.
It is more expensive,
and forces users to to grant their Encryptors 
`KMS:Decrypt` permission. 

(The permission issue is the real blocker.
Limiting an actor to Encrypt ONLY is a security best practice.)

If you can convince your clients to grant you `GenerateDataKey` 
permission, you will be saving them money,
and increase the value of their KMS Keys entries in CloudTrail logs,
as they will be able to distinguish Encrypt vs Decrypt.

@disrael-globality , I am going to close this issue.
If you have other questions, feel free to open another Issue.
