### ISSUE TITLE
Support decryption using KmsMasterKeys built using alias ARNs

### ISSUE THREAD

**Issue by bdonlan** [aws/aws-encryption-sdk-java#27]
Because the KMSMasterKey compares the key info field against its ARN, and the key info field is always a full key ID ARN, decryption using a KMSMasterKey using either a bare key ID or a key alias will always fail.

Previously reported in #21.

**Comment by bdonlan** [comment]
Without changes to KMS this would require resolving the alias to a key ID. Unfortunately the DescribeKey API has a low request rate limit which means we'd need to cache it quite heavily - at which point alias changes might have unexpected delays associated with them.

Alternately we could do a dummy Encrypt/GenerateDataKey/ReEncrypt call to resolve the alias to a specific key ID. This doubles data plane operation load.

Either option requires additional IAM permissions to perform the alias resolution, so this isn't a very satisfactory solution.

**Comment by outime** [comment]
@bdonlan any update? It'd be great to have this

**Comment by mattsb42-aws** [comment]
@outime Is there a specific issue that you are trying to address by using a `KMSMasterKey` with an alias for decrypt rather than using a `KMSMasterKeyProvider`? I wonder if there might be a better way that we could solve that problem.

For all of the reasons that @bdonlan mentioned, I think that anything that enabled this on the client side would be at best a potentially sharp edge, and we try to avoid those wherever we can.

**Comment by eschulma** [comment]
It would be nice to have so that test and production accounts can use the same alias for the key, and it would also also multi-region keys with the same alias.

Also you should arguably reopen #21 or combine it here -- I thought that issue had been fixed and was beating my head on the wall for quite a while.

**Comment by mattsb42-aws** [comment]
@eschulma Could you elaborate on what you are trying to do? That sounds like a use case that would be better addressed on decrypt by using `KMSMasterKeyProvider` rather than using a `KMSMasterKey` with an alias.

Re #21, this issue was created to track the feature request that arose from that issue. Is there anything that would have helped clarify that aside from @bdonlan's closing comment?

**Comment by dankirkd** [comment]
Reviving this thread to inquire about how one would implement manual key rotation leveraging an alias, as described at https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html ?

It was my hope that by using an alias instead of the key id I could abstract the reference.  If that's not feasible due to concerns of overhead looking up the key id, what is the recommended approach?

**Comment by farleyb-amazon** [comment]
Hi dankirkd,

If looking up key ids isn't feasible, one approach you could take is to use a master key provider in "discovery" mode. This will allow decryption of ciphertexts from any CMK. If you do this, we do recommend using a DiscoveryFilter, which will limit the allowed CMKs to a specific set of AWS accounts and AWS partition.

You can find an example of this here: https://github.com/aws/aws-encryption-sdk-java/blob/1aaa4c5c13979e0c4d5bf000e58c23524fee56a6/src/examples/java/com/amazonaws/crypto/examples/DiscoveryDecryptionExample.java#L77-L92 

I'm going to go ahead and close this out, but please feel free to re-open or cut another issue if you have any other questions.

Thanks,
Ben

**Comment by 2ps** [comment]
> o address by using a `KMSMasterKey` with an alias for decrypt rather than using a `KMSMasterKeyProvider`

I am using the `KMSMasterKeyProvider` with v2.4.0 of the encryption sdk, and I still get this error.
