### ISSUE TITLE
MultiRegion Key replica required in encryption key ring (not as expected.

### ISSUE THREAD

**Issue by anupadki23** [aws/aws-encryption-sdk-java#271]
I am trying to get the cmk  multi-region/primary/replica keys working from aws encryption SDK aka awsCrypto.
Created the keys and the users to access the keys ref:
https://aws.amazon.com/about-aws/whats-new/2021/06/kms-multi-region-keys/ 
When I tried a java program with this set up, I expected it to work as below
Encrypt with mrk primary
Decrypt with a replica key
However the decrypt happens only if I include the replica key in encryption key , tried with KmsMasterKeyProvider and KmsMasterKeyProvider, that defeats the purpose of using the primary/replica, this works just like when we crate two separate keys in different region. 
Ref: updated encryption sdk version to 2.3. 0 treid https://github.com/aws/aws-encryption-sdk-java/blob/master/src/examples/java/com/a[…]naws/crypto/examples/DiscoveryMultiRegionDecryptionExample.java 

Tried it just like the blog example.

**Comment by texastony** [comment]
anupadik23

Thank you for reaching out.

You say you tried it with the "`KmsMasterKeyProvider` and `KmsMasterKeyProvider`"... did you mean the `AwsKmsMrkAwareMasterKeyProvider` ? I am almost certain you did, because you were following the `DiscoveryMultiRegionDecryptionExample`.

The only other explanation I can think of is that there is something wonky with your Key Policies or IAM policy. Can you describe how you are testing this? Are you encrypting and decrypting on the same instance/computer?

If not, do the different endpoints have the same level of Key access?
Also, could you share with us the stack trace or error message you are receiving?

Much Obliged
[crypto-tools](https://github.com/aws/crypto-tools)

**Comment by texastony** [comment]
Howdy @anupadki23

If you are still having an issue, please re-open and comment with more details.

Much Obliged,
AWS Crypto Tools
